
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FRACTIONAL_DURATION OCTAVE PITCH VOICE WHOLE_DURATIONsong : song voicesong : voicevoice : voice notevoice : VOICE notenote : FRACTIONAL_DURATION PITCH OCTAVE\n            | WHOLE_DURATION PITCH OCTAVE'
    
_lr_action_items = {'VOICE':([0,1,2,4,5,8,11,12,],[3,3,-2,-1,-3,-4,-5,-6,]),'$end':([1,2,4,5,8,11,12,],[0,-2,-1,-3,-4,-5,-6,]),'FRACTIONAL_DURATION':([2,3,4,5,8,11,12,],[6,6,6,-3,-4,-5,-6,]),'WHOLE_DURATION':([2,3,4,5,8,11,12,],[7,7,7,-3,-4,-5,-6,]),'PITCH':([6,7,],[9,10,]),'OCTAVE':([9,10,],[11,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'song':([0,],[1,]),'voice':([0,1,],[2,4,]),'note':([2,3,4,],[5,8,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> song","S'",1,None,None,None),
  ('song -> song voice','song',2,'p_song','parser.py',44),
  ('song -> voice','song',1,'p_song_voice','parser.py',48),
  ('voice -> voice note','voice',2,'p_voice','parser.py',52),
  ('voice -> VOICE note','voice',2,'p_voice_note','parser.py',58),
  ('note -> FRACTIONAL_DURATION PITCH OCTAVE','note',3,'p_note','parser.py',65),
  ('note -> WHOLE_DURATION PITCH OCTAVE','note',3,'p_note','parser.py',66),
]
