
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'PITCHsong : song notesong : notenote : PITCH'
    
_lr_action_items = {'PITCH':([0,1,2,3,4,],[3,3,-2,-3,-1,]),'$end':([1,2,3,4,],[0,-2,-3,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'song':([0,],[1,]),'note':([0,1,],[2,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> song","S'",1,None,None,None),
  ('song -> song note','song',2,'p_song','parser.py',22),
  ('song -> note','song',1,'p_song_note','parser.py',28),
  ('note -> PITCH','note',1,'p_note','parser.py',35),
]
